// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:barbero/models/appointment.dart';
import 'package:barbero/models/appointment_type.dart';
import 'package:barbero/models/client.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppointmentAdapter());
    registerAdapter(AppointmentStatusAdapter());
    registerAdapter(AppointmentTypeAdapter());
    registerAdapter(ClientAdapter());
  }
}
